### ISSUE TITLE
Logging at class level

### ISSUE THREAD

**Issue by thamdurai** [LenarBad/EasyLog#7]
Logging works great with method level. It would be nice to have logging at class level.

**Comment by LenarBad** [comment]
A question for you,
What annotation names would be the best for the method level and the class level?

Now we have:
1. ```@LogCall``` on the method level for service calls
2. ```@LogMethod``` on the method level for regular methods

As a possible option we can use:
1. ```@LogCall``` on the method level for service calls
2. ```@LogService``` on the class level for service calls
3. ```@LogMethod``` on the method level for regular methods
4. ```@LogMethods``` on the class level for regular methods

or we can use ```@LogService``` on both method and class levels for service calls.

any other suggestions?

**Comment by LenarBad** [comment]
Implemented in _**0.1.0**_
1. ```@LogCall``` on the method level for service calls
2. ```@LogCalls``` on the class level for service calls
3. ```@LogMethod``` on the method level for regular methods
4. ```@LogMethods``` on the class level for regular methods
